### ISSUE TITLE
Rewrite Simulation Software in Pure Gazebo

### ISSUE THREAD

**Issue by Namr** [ncsurobotics/Seawolf-8-Software#33]
The current simulation setup on master is clunky and requires too many dependencies that are difficult to get (and all have issues). The entire system should be rewritten to only use Gazebo and ROS based dependencies.

# Subtasks
- [ ] Write gazebo plugins to control a Seawolf 8 model
- [ ] Write corresponding serial node for that plugin
- [ ] Rewrite tests to work in this new environment
- [ ] Change docker setup to work with the new sim
- [ ] Wiki pages must be updated
